version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 058264342822.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mixtral_cpu:dev --build-arg S3_BUCKET=mixtralbucket .
      - docker tag mixtral_cpu:dev 058264342822.dkr.ecr.eu-central-1.amazonaws.com/rvrecht:dev
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 058264342822.dkr.ecr.eu-central-1.amazonaws.com/rvrecht:dev
artifacts:
  files:
    - '**/*'
  discard-paths: yes
